### PR TITLE
feat(cli): improve tests for create command

### PR DESCRIPTION
**Pull request by Niraj-Kamdar**
- Closes: #907

### CODE REVIEW

**Review by cbrzn — COMMENTED** [review]
Hey Niraj thanks for start a tackle on this :pray:

I was thinking that this is not the approach we want to take if we want to close #907 - I think instead we should create a new file in `__tests__/unit/` folder named `create.spec.ts` and basically try to run the functions from there and check if the behavior is the expected.

For example, I thought that we can follow these approaches:
https://github.com/tj/commander.js/issues/438#issuecomment-274285003
https://github.com/tj/commander.js/issues/1565#issuecomment-879661279
and execute every method of instance?

Another approach we can take is to (talking from the context of `create` tests) execute the `run` function and see if it indeed creates a folder for example

Note that the objective of these approaches is to be able to take up our code coverage, as you mentioned before :-D

**Comment by Niraj-Kamdar** [comment]
@cbrzn I'd still keep e2e tests, we just need to add unit tests.

**Comment by cbrzn** [comment]
> @cbrzn I'd still keep e2e tests, we just need to add unit tests.

That's correct! I would remove the `closes ...` from the description and just make this an improvement of the current integration tests. As we talked before, let's tackle the unit tests post alpha

**Review by dOrgJelli — APPROVED** [review]
This is really nice @Niraj-Kamdar :clap:

**Comment by dOrgJelli** [comment]
Also IMO @cbrzn @Niraj-Kamdar I think this fully tests the `create` functionality, so I'm not sure we need unit tests if the e2e tests can exercise all functionality.

**Pull request merged**
