### PR TITLE
CLI - Revert `build` command to --no-codegen instead of --codegen

### LINKED ISSUE #1516: CLI - `build` command - revert `--codegen` to `--no-codegen` option
**Is your feature request related to a problem? Please describe.**
As part of https://github.com/polywrap/toolchain/pull/1385 we've changed `polywrap build` to not run codegen by default, and accept a `--codegen` option. Before this, it would run codegen by default and we had a `--no-codegen` option.

**Describe the solution you'd like**
We want to revert back to `--no-codegen` because the internal consensus is that it's going to be the preferred way of running `build`.

### PR DESCRIPTION
**Pull request by pileks**
**Marked as Draft until we reach consensus regarding how the layout of these features should look like**

Closes #1516 

This PR reverts the `--codegen` option of the `build` command back to `--no-codegen`.

Essentially, the `build` command will now run `codegen` by default once again.

**Important caveat:** The `-n` shorthand for the `--no-codegen` option has not been brought back. This is a personal style decision, please comment whether you agree. 😄

### CODE REVIEW

**Comment by krisbitney** [comment]
What are the arguments for and against this? I kind of like the current state of things (requiring `--codegen`).

**Comment by cbrzn** [comment]
@krisbitney you can check the conv here https://discord.com/channels/796821176743362611/1010304976406454323/1069951628943306805

**Comment by krisbitney** [comment]
> @krisbitney you can check the conv here https://discord.com/channels/796821176743362611/1010304976406454323/1069951628943306805

Okay, I see. Sounds good to me!

**Comment by krisbitney** [comment]
I'd be happy to approve this once tests are passing

**Review by dOrgJelli — DISMISSED** [review]

**Pull request merged**
