### PR TITLE
Module Agnostic Schema Binding

### PR DESCRIPTION
**Pull request by dOrgJelli**
Make the schema bind project "module agnostic", where it can handle being given an array of arbitrary named modules, and generated bindings for each one of them. Additionally, support for macro-level concepts like "entry point files" and "common type folders" can be implemented in the individual bindings themselves.

For example:
- The plugin-ts & app-ts bindings can create entry point modules.
- The wasm-as binding can generate a common type folder.

### CODE REVIEW

**Comment by dOrgJelli** [comment]
Just went through the code one more time, pretty confident about its current state. @krisbitney @nerfZael @Niraj-Kamdar could I get 2 sign offs when you have a moment? LMK if you have any questions or would like a walk-through of the PR.

**Review by krisbitney — DISMISSED** [review]
LGTM

**Review by namesty — DISMISSED** [review]
LGTM

**Review by Niraj-Kamdar — DISMISSED** [review]
LGTM

**Pull request merged**
