### PR TITLE
fix: release-pr workflow use pull_request.head.ref

### PR DESCRIPTION
**Pull request by dOrgJelli**

### CODE REVIEW

**Comment by dOrgJelli** [comment]
/workflows/release-pr

**Comment by polywrap-release-forks** [comment]
[Building Release PR](https://github.com/polywrap/monorepo/actions/runs/2620790211) (`0.1.0`)

**Comment by polywrap-release-forks** [comment]
**[Release PR Created](https://github.com/polywrap/monorepo/pull/) (`0.1.0`)**

**Comment by polywrap-release-forks** [comment]
[Building Release PR](https://github.com/polywrap/monorepo/actions/runs/2620790211) (`0.1.0`)

**Comment by polywrap-release-forks** [comment]
**[Release PR Created](https://github.com/polywrap/monorepo/pull/) (`0.1.0`)**

**Pull request merged**
