### PR TITLE
0.9 feat: add retries to ipfs resolver plugin

### PR DESCRIPTION
**Pull request by krisbitney**
This non-breaking change would be a huge improvement for the uniswap v3 front end, and I imagine the EthForAll hackers

### CODE REVIEW

**Review by Niraj-Kamdar — APPROVED** [review]
LGTM!

**Comment by Niraj-Kamdar** [comment]
How about also adding auth support with env?

**Review by dOrgJelli — APPROVED** [review]
Do we have the equivalent of this in 0.10?

**Comment by krisbitney** [comment]
> Do we have the equivalent of this in 0.10?

Yeah, we do. I know you saw the other PRs related to this since your comment. It's a really great feature!

**Pull request merged**
